apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-operator-sm
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ai-operator
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default
