apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-receiver
  namespace: monitoring
  labels:
    app: alert-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-receiver
  template:
    metadata:
      labels:
        app: alert-receiver
    spec:
      containers:
      - name: alert-receiver
        # Replace the image below with the image you build and push
        image: ghcr.io/aashish-26/ai-sre-alert-receiver:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: alert-receiver
  namespace: monitoring
spec:
  selector:
    app: alert-receiver
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
